#!/bin/bash

RMA="/booleanfs/sahoo/softwares/USF-softwares/affy-apps/rma/rma"

$RMA -o $1-expr.txt \
  --rank-list="/booleanfs/sahoo/Data1/GEXC/Affy/golden-u133plus2" \
  -c /booleanfs/sahoo/CDF --cel-list=filelist

